### ISSUE TITLE
Full spec editor issue

### ISSUE THREAD

**Issue by Kaori17** [qiangqiang101/Initial-D-Arcade-Stage-Teknoparrot-Launcher#1]
Cannot save full spec on card's editor

**Comment by qiangqiang101** [comment]
which car are you using?
is there any error message when you click save? what is it?

**Comment by Kaori17** [comment]
I'm using ae86(Trueno)/(also tried keisuke's FD), i've tried all of the slots, and no, there is no error message.

**Comment by qiangqiang101** [comment]
try the latest 2.7.1 should be fixed.
